### PR TITLE
SL-145 Fix recording importer pg restart issue#239

### LINKED ISSUE #239: scalelite-recording-importer not reconnecting database
After a restart of our postgresql server holding the scalelite database the scalelite-recording-importer stopped to work, 
because it did not reconnect to the database. Other services like scalelite-api and scalelite-poller worked without problems after the restart, but the importer had to be restarted.

ERROR -- : Failed to import recording: PG::UnableToSend: no connection to the server

On this error it should try to reconnect.

### PR DESCRIPTION
**Pull request by amalrails**
Closes #239

### CODE REVIEW

File: config/application.rb [hunk 1]
```diff
@@ -108,5 +108,8 @@ class Application < Rails::Application
 
     # Scalelite Host name
     config.x.url_host = ENV['URL_HOST']
+
+    # DB connection retry attempt counts
+    config.x.db_connection_retry_count = ENV.fetch('DB_CONNECTION_RETRY_COUNT', '3').to_i
```
Comment (jfederico) [inline config/application.rb:113]: Is `DB_CONNECTION_RETRY_COUNT` documented?

**Review by jfederico — CHANGES_REQUESTED** [review]

**Review by jfederico — APPROVED** [review]
