### PR TITLE
SL-275: Removed hardcoded SHA256 checksum from BBB calls

### LINKED ISSUE #905: Servers not coming online when enforcing SHA512 checksum
**Describe the bug**
When scalelite is configured to enforce a SHA512 checkum algorithm, servers fail to come online

**To Reproduce**
docker-compose configured to run images
```
CONTAINER ID   IMAGE                                                                    COMMAND                  CREATED          STATUS          PORTS                          NAMES
e1ad6103355b   blindsidenetwks/nginx:amazonlinux-2.0.20221004.0                         "/bin/bash -c 'envsu…"   10 minutes ago   Up 10 minutes   80/tcp, 0.0.0.0:443->443/tcp   scalelite-proxy
38ef91e7586b   blindsidenetwks/scalelite:v1.4-bionic240-amazonlinux                     "/bin/sh -c 'update-…"   10 minutes ago   Up 10 minutes   3000/tcp                       scalelite-poller
769a1b5fec7a   bigbluebutton/bbb-playback-proxy:bionic-240-amazonlinux-2.0.20221004.0   "/etc/nginx/start -g…"   10 minutes ago   Up 10 minutes   80/tcp                         scalelite-recordings
ba58c1b7d88a   blindsidenetwks/scalelite:v1.4-bionic240-amazonlinux                     "/bin/sh -c 'update-…"   10 minutes ago   Up 10 minutes   3000/tcp                       scalelite-api
```

scalelite-poller container environment settings
```
HOSTNAME=38ef91e7586b
LOADBALANCER_CHECKSUM_ALGORITHM=SHA512
TERM=xterm
REDIS_URL=rediss://xxxxxxxxxxxxxxxxxxxxx:6379
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/srv/scalelite
SHLVL=1
HOME=/root
RAILS_ENV=production
TINI_VERSION=v0.19.0
RAILS_LOG_TO_STDOUT=false
BUILD_NUMBER=v1.4
_=/usr/bin/env
```
scalelite-poller log
```
I, [2023-04-19T00:17:31.305713 #15]  INFO -- : Server id=bbb2.mountcorona.com offline load: unavailable
W, [2023-04-19T00:17:31.306516 #15]  WARN -- : Failed to get server id=bbb1.mountcorona.com status: checksumError: Checksums do not match
I, [2023-04-19T00:17:31.307196 #15]  INFO -- : Server id=bbb1.mountcorona.com offline load: unavailable
D, [2023-04-19T00:18:31.353020 #15] DEBUG -- : Polling meetings
D, [2023-04-19T00:18:31.353259 #15] DEBUG -- : Polling servers
D, [2023-04-19T00:18:31.355437 #15] DEBUG -- : Polling Server id=bbb2.mountcorona.com
D, [2023-04-19T00:18:31.355492 #15] DEBUG -- : Polling Server id=bbb1.mountcorona.com
W, [2023-04-19T00:18:31.367594 #15]  WARN -- : Failed to get server id=bbb1.mountcorona.com status: checksumError: Checksums do not match
W, [2023-04-19T00:18:31.367706 #15]  WARN -- : Failed to get server id=bbb2.mountcorona.com status: checksumError: Checksums do not match
```

***Steps to reproduce the behavior:***
1. BBB servers configured `/etc/bigbluebutton/bbb-web.properties` with
```
supportedChecksumAlgorithms=sha512
```
Confirmed with api mate performing a `getMeetings`

3. Scalelite deployed through Scalelite Enterprise

**Expected behavior**
Servers to come online

### PR DESCRIPTION
**Pull request by farhatahmad**
fixes #905 
## Description

By default, Scalelite was hardcoded to always use SHA256 when making API calls to BBB. The environment variable `LOADBALANCER_CHECKSUM_ALGORITHM` allowed system admins to specify which algorithms can be used to verify the Scalelite checksum, but not the BBB checksum.

1. If not set, Scalelite will accept SHA1, SHA256, SHA512 requests and use SHA256 for requests to BBB
2. If set, Scalelite will accept whatever values are set, and use the most secure option for requests to BBB

## Testing Steps

1- Enabled SHA512 on your BBB server
2- Set `LOADBALANCER_CHECKSUM_ALGORITHM=SHA512`
3- Send a create call to Scalelite, using a SHA512 checksum
4- Ensure the request goes through without failing

### CODE REVIEW

File: app/controllers/concerns/api_helper.rb [hunk 1]
```diff
@@ -20,7 +20,7 @@ def verify_checksum
     raise ChecksumError if params[:checksum].blank?
     raise ChecksumError if secrets.empty?
 
-    checksum_algorithm = case params[:checksum].length
+    algorithm = case params[:checksum].length
```
Comment (farhatahmad) [inline app/controllers/concerns/api_helper.rb:23]: renaming this variable to avoid confusion

**Review by jfederico — APPROVED** [review]
